services:
  h24app_dev_web:
    container_name: h24app_dev_web
    image: ${DOCKER_H24APP_IMAGE}
    platform: linux/amd64
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - ../.env
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.h24app_dev_web.rule=Host(`develop.h24transports.com`)"
      - "traefik.http.routers.h24app_dev_web.entrypoints=https"
      - "traefik.http.routers.h24app_dev_web.tls.certresolver=h24dev"
      - "traefik.http.routers.h24app_dev_web.middlewares=dev-no-crawl@file"
      - "traefik.http.services.h24app_dev_web.loadbalancer.server.port=8080"
    networks:
      - h24app_dev_traefik

networks:
  h24app_dev_traefik:
    name: h24app_dev_traefik
    external: true
