services:
  h24_dev_appserver:
    container_name: h24_dev_appserver
    image: ${DOCKER_H24APP_IMAGE}
    platform: linux/amd64
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=8080
    env_file:
      - ../.env
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.h24_dev_appserver.rule=Host(`develop.h24transports.com`)"
      - "traefik.http.routers.h24_dev_appserver.entrypoints=https"
      - "traefik.http.routers.h24_dev_appserver.tls.certresolver=h24dev"
      - "traefik.http.routers.h24_dev_appserver.middlewares=dev-no-crawl@file"
      - "traefik.http.services.h24_dev_appserver.loadbalancer.server.port=8080"
    networks:
      - h24_dev_traefik

networks:
  h24_dev_traefik:
    name: h24_dev_traefik
    external: true
