services:
  h24_appserver:
    container_name: h24_appserver
    image: ${DOCKER_H24APP_IMAGE}
    platform: linux/amd64
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=8080
    env_file:
      - ../.env
      - .env
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.h24_appserver.rule=Host(`h24transports.com`) || Host(`www.h24transports.com`)"
      - "traefik.http.routers.h24_appserver.entrypoints=https"
      - "traefik.http.routers.h24_appserver.tls.certresolver=h24prod"
      - "traefik.http.services.h24_appserver.loadbalancer.server.port=8080"
    networks:
      - h24_traefik

networks:
  h24_traefik:
    name: h24_traefik
    external: true
