name: Deploy H24 Transport App

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    uses: ./.github/workflows/reusable-deploy.yml
    secrets: inherit
    with:
      dockerfile_path: 'docker/images/nginx/Dockerfile'

  notify:
    needs: [deploy]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Deployment notification
        run: |
          if [[ "${{ needs.deploy.result }}" == "success" ]]; then
            echo "✅ Déploiement réussi!"
            echo "🌍 Environnement: ${{ needs.deploy.outputs.environment }}"
            echo "📦 Image: ${{ needs.deploy.outputs.image_tag }}"
          else
            echo "❌ Échec du déploiement"
            exit 1
          fi
